//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_sRegiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_sRegiones()
        {
            this.ACC_dPerfiles = new HashSet<ACC_dPerfiles>();
        }
    
        public short id { get; set; }
        public string descripcion { get; set; }
        public string descripcionCorta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_dPerfiles> ACC_dPerfiles { get; set; }
    }
}
