//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_dAplicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_dAplicaciones()
        {
            this.ACC_dAcciones = new HashSet<ACC_dAcciones>();
            this.ACC_dMenu = new HashSet<ACC_dMenu>();
            this.ACC_dPerfiles = new HashSet<ACC_dPerfiles>();
            this.ACC_rdMenu_dAcciones = new HashSet<ACC_rdMenu_dAcciones>();
        }
    
        public string id { get; set; }
        public string descripcion { get; set; }
        public string idEstado { get; set; }
        public string accesos { get; set; }
        public System.DateTime ts { get; set; }
        public string esPocket { get; set; }
        public string tooltip { get; set; }
        public string imagen { get; set; }
        public string url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_dAcciones> ACC_dAcciones { get; set; }
        public virtual ACC_sEstados ACC_sEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_dMenu> ACC_dMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_dPerfiles> ACC_dPerfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_rdMenu_dAcciones> ACC_rdMenu_dAcciones { get; set; }
    }
}
