//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_dUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_dUsuarios()
        {
            this.ACC_rdUsuarios_dPerfiles_dAcciones = new HashSet<ACC_rdUsuarios_dPerfiles_dAcciones>();
        }
    
        public short id { get; set; }
        public string usuarioAD { get; set; }
        public string legajo { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public System.DateTime fhAlta { get; set; }
        public Nullable<System.DateTime> fhBaja { get; set; }
        public string idEstado { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
        public string email { get; set; }
    
        public virtual ACC_sEstados ACC_sEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_rdUsuarios_dPerfiles_dAcciones> ACC_rdUsuarios_dPerfiles_dAcciones { get; set; }
    }
}
