//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_dMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_dMenu()
        {
            this.ACC_rdMenu_dAcciones = new HashSet<ACC_rdMenu_dAcciones>();
        }
    
        public short id { get; set; }
        public string idAplicacion { get; set; }
        public Nullable<short> idMenu_Precede { get; set; }
        public short orden { get; set; }
        public string nombre { get; set; }
        public string tooltip { get; set; }
        public string descripcion { get; set; }
        public string idEstado { get; set; }
        public string imagen { get; set; }
        public Nullable<short> usuariosMaximos { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
        public string url { get; set; }
    
        public virtual ACC_dAplicaciones ACC_dAplicaciones { get; set; }
        public virtual ACC_sEstados ACC_sEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_rdMenu_dAcciones> ACC_rdMenu_dAcciones { get; set; }
    }
}
