//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_rdUsuarios_dPerfiles_dAcciones
    {
        public short idUsuario { get; set; }
        public decimal idPerfilAccion { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
    
        public virtual ACC_dUsuarios ACC_dUsuarios { get; set; }
        public virtual ACC_rdPerfil_dAcciones ACC_rdPerfil_dAcciones { get; set; }
    }
}
