//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_rdMenu_dAcciones
    {
        public string idAplicacion { get; set; }
        public short idMenu { get; set; }
        public short idAccion { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
    
        public virtual ACC_dAcciones ACC_dAcciones { get; set; }
        public virtual ACC_dAplicaciones ACC_dAplicaciones { get; set; }
        public virtual ACC_dMenu ACC_dMenu { get; set; }
    }
}
