//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua_Accesos.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccesosSUAEntities : DbContext
    {
        public AccesosSUAEntities()
            : base("name=AccesosSUAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC_dAcciones> ACC_dAcciones { get; set; }
        public virtual DbSet<ACC_dAplicaciones> ACC_dAplicaciones { get; set; }
        public virtual DbSet<ACC_dMenu> ACC_dMenu { get; set; }
        public virtual DbSet<ACC_dPerfiles> ACC_dPerfiles { get; set; }
        public virtual DbSet<ACC_dUsuarios> ACC_dUsuarios { get; set; }
        public virtual DbSet<ACC_rdPerfil_dAcciones> ACC_rdPerfil_dAcciones { get; set; }
        public virtual DbSet<ACC_rdUsuarios_dPerfiles_dAcciones> ACC_rdUsuarios_dPerfiles_dAcciones { get; set; }
        public virtual DbSet<ACC_sEstados> ACC_sEstados { get; set; }
        public virtual DbSet<ACC_sRegiones> ACC_sRegiones { get; set; }
        public virtual DbSet<ACC_rdMenu_dAcciones> ACC_rdMenu_dAcciones { get; set; }
    }
}
