//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua.IWMS.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;
    
    public interface IContextCDsEntities : IDisposable 
    {
        IEnumerable<INV_dDocumentos_SelectxLegajo_Result> INV_dDocumentos_SelectxLegajo (string legajo);
        IEnumerable<Nullable<bool>> INV_dPosiciones_ReiniciarDocumento (Nullable<int> idDoc);
        IEnumerable<INV_dPosiciones_SelectByDocumento_Result> INV_dPosiciones_SelectByDocumento (Nullable<int> idDoc);
        IEnumerable<INV_dPosiciones_SelectDisponible_Result> INV_dPosiciones_SelectDisponible (Nullable<int> idDoc);
        IEnumerable<Nullable<bool>> INV_dPosiciones_Update (Nullable<int> id, string usuario, string digito, Nullable<double> bultosInv, string usuarioInventario, Nullable<int> hxPInv, Nullable<int> cajasSueltasInv, string observaciones, string codigoArticulo);
        IEnumerable<string> INV_dPosiciones_ValidarYCrearControles (Nullable<int> idDoc);
        DbContextTransaction BeginTransaction();
        int SaveChanges(bool isMNAEntities);
        void Commit(DbContextTransaction transaction);
        void RollbackTransaction(DbContextTransaction transaction);
    } // End Interface
    
    
    public partial class CDsEntities : DbContext, IContextCDsEntities
    {
        public CDsEntities()
            : base("name=CDsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual IEnumerable<INV_dDocumentos_SelectxLegajo_Result> INV_dDocumentos_SelectxLegajo(string legajo)
        {
            var legajoParameter = legajo != null ?
                new ObjectParameter("legajo", legajo) :
                new ObjectParameter("legajo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INV_dDocumentos_SelectxLegajo_Result>("INV_dDocumentos_SelectxLegajo", legajoParameter);
        }
    
        public virtual IEnumerable<Nullable<bool>> INV_dPosiciones_ReiniciarDocumento(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("INV_dPosiciones_ReiniciarDocumento", idDocParameter);
        }
    
        public virtual IEnumerable<INV_dPosiciones_SelectByDocumento_Result> INV_dPosiciones_SelectByDocumento(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INV_dPosiciones_SelectByDocumento_Result>("INV_dPosiciones_SelectByDocumento", idDocParameter);
        }
    
        public virtual IEnumerable<INV_dPosiciones_SelectDisponible_Result> INV_dPosiciones_SelectDisponible(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INV_dPosiciones_SelectDisponible_Result>("INV_dPosiciones_SelectDisponible", idDocParameter);
        }
    
        public virtual IEnumerable<Nullable<bool>> INV_dPosiciones_Update(Nullable<int> id, string usuario, string digito, Nullable<double> bultosInv, string usuarioInventario, Nullable<int> hxPInv, Nullable<int> cajasSueltasInv, string observaciones, string codigoArticulo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var digitoParameter = digito != null ?
                new ObjectParameter("Digito", digito) :
                new ObjectParameter("Digito", typeof(string));
    
            var bultosInvParameter = bultosInv.HasValue ?
                new ObjectParameter("BultosInv", bultosInv) :
                new ObjectParameter("BultosInv", typeof(double));
    
            var usuarioInventarioParameter = usuarioInventario != null ?
                new ObjectParameter("UsuarioInventario", usuarioInventario) :
                new ObjectParameter("UsuarioInventario", typeof(string));
    
            var hxPInvParameter = hxPInv.HasValue ?
                new ObjectParameter("HxPInv", hxPInv) :
                new ObjectParameter("HxPInv", typeof(int));
    
            var cajasSueltasInvParameter = cajasSueltasInv.HasValue ?
                new ObjectParameter("CajasSueltasInv", cajasSueltasInv) :
                new ObjectParameter("CajasSueltasInv", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var codigoArticuloParameter = codigoArticulo != null ?
                new ObjectParameter("CodigoArticulo", codigoArticulo) :
                new ObjectParameter("CodigoArticulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("INV_dPosiciones_Update", idParameter, usuarioParameter, digitoParameter, bultosInvParameter, usuarioInventarioParameter, hxPInvParameter, cajasSueltasInvParameter, observacionesParameter, codigoArticuloParameter);
        }
    
        public virtual IEnumerable<string> INV_dPosiciones_ValidarYCrearControles(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INV_dPosiciones_ValidarYCrearControles", idDocParameter);
        }
    
    	public DbContextTransaction BeginTransaction()
    	{
    		return this.Database.BeginTransaction();
    	}
    
    	public int SaveChanges(bool isMNAEntities)
    	{
    		if (isMNAEntities)
    			return this.SaveChanges();
    
    		return -1;
    	}
    
    	public void Commit(DbContextTransaction transaction)
    	{
    		transaction.Commit();
    		transaction.Dispose();
    	}
    
    	public void RollbackTransaction(DbContextTransaction transaction)
    	{
    		transaction.Rollback();
    		transaction.Dispose();
    	}
    
    } // End Class

} // End Namespace
