//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua.Inventario.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_dCCsActivos
    {
        public decimal id { get; set; }
        public byte idRegion { get; set; }
        public decimal cc { get; set; }
        public string descripcion { get; set; }
        public decimal idb { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
        public string estado { get; set; }
    }
}
