//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua.Inventario.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_dPosiciones
    {
        public int id { get; set; }
        public int idDocumento { get; set; }
        public string sector { get; set; }
        public string pasillo { get; set; }
        public Nullable<double> columna { get; set; }
        public Nullable<double> nivel { get; set; }
        public Nullable<double> compart { get; set; }
        public string etiqueta { get; set; }
        public string ean13 { get; set; }
        public string descripcion { get; set; }
        public string proveedor { get; set; }
        public string id_orden_compra { get; set; }
        public Nullable<System.DateTime> fecha_hora_recepcion { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public Nullable<double> vidautil { get; set; }
        public string diasvencer { get; set; }
        public Nullable<double> cxh { get; set; }
        public Nullable<double> hxp { get; set; }
        public Nullable<double> uxb { get; set; }
        public Nullable<double> uxpack { get; set; }
        public Nullable<double> bultos { get; set; }
        public Nullable<double> packs { get; set; }
        public Nullable<double> unidades { get; set; }
        public string recepcionista { get; set; }
        public string almacenador { get; set; }
        public string estadocalidad { get; set; }
        public Nullable<double> cara { get; set; }
        public string usuario { get; set; }
        public string digito { get; set; }
        public Nullable<double> bultosinv { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<System.DateTime> fechaact { get; set; }
        public string usuarioinventario { get; set; }
        public string tipoinventario { get; set; }
        public Nullable<int> hxpinv { get; set; }
        public Nullable<int> cajassueltasinv { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
        public string codigoarticulo { get; set; }
        public string tipolectura { get; set; }
        public string documentoasociado { get; set; }
    
        public virtual INV_dDocumentos INV_dDocumentos { get; set; }
    }
}
