//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua.Inventario.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_dCCsActivos
    {
        public decimal id { get; set; }
        public byte idRegion { get; set; }
        public decimal cc { get; set; }
        public string descripcion { get; set; }
        public decimal idb { get; set; }
        public string usuario { get; set; }
        public System.DateTime ts { get; set; }
        public string estado { get; set; }
    }
}
