//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua.Inventario.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_dDocumentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_dDocumentos()
        {
            this.INV_dPosiciones = new HashSet<INV_dPosiciones>();
        }
    
        public int id { get; set; }
        public string Documento { get; set; }
        public string LegajoAsignado { get; set; }
        public short Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> idInventario { get; set; }
        public Nullable<int> Fase { get; set; }
        public Nullable<int> idDocumentoPadre { get; set; }
        public string UltimoLegajoAsignado { get; set; }
        public Nullable<bool> ImpactadoSega { get; set; }
    
        public virtual INV_dInventario INV_dInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_dPosiciones> INV_dPosiciones { get; set; }
    }
}
