//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corp.Cencosud.Supermercados.Sua.Inventario.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CDsEntities : DbContext
    {
        public CDsEntities()
            : base("name=CDsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INV_dInventario> INV_dInventario { get; set; }
        public virtual DbSet<INV_dPosiciones> INV_dPosiciones { get; set; }
        public virtual DbSet<INV_dCCsActivos> INV_dCCsActivos { get; set; }
        public virtual DbSet<INV_dDocumentos> INV_dDocumentos { get; set; }
    
        public virtual ObjectResult<string> INV_dPosiciones_ValidarYCrearControles(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INV_dPosiciones_ValidarYCrearControles", idDocParameter);
        }
    
        public virtual ObjectResult<string> INV_dPosiciones_CrearControlForzado(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INV_dPosiciones_CrearControlForzado", idDocParameter);
        }
    
        public virtual ObjectResult<INV_EstadoActual_Result> INV_EstadoActual(Nullable<int> idInventario, Nullable<int> fase)
        {
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("IdInventario", idInventario) :
                new ObjectParameter("IdInventario", typeof(int));
    
            var faseParameter = fase.HasValue ?
                new ObjectParameter("Fase", fase) :
                new ObjectParameter("Fase", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INV_EstadoActual_Result>("INV_EstadoActual", idInventarioParameter, faseParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INV_dPosiciones_AjusteSega(Nullable<int> idDoc)
        {
            var idDocParameter = idDoc.HasValue ?
                new ObjectParameter("idDoc", idDoc) :
                new ObjectParameter("idDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INV_dPosiciones_AjusteSega", idDocParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> INV_dPosiciones_Update(Nullable<int> id, string usuario, string digito, Nullable<double> bultosInv, string usuarioInventario, Nullable<int> hxPInv, Nullable<int> cajasSueltasInv, string observaciones, string codigoArticulo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var digitoParameter = digito != null ?
                new ObjectParameter("Digito", digito) :
                new ObjectParameter("Digito", typeof(string));
    
            var bultosInvParameter = bultosInv.HasValue ?
                new ObjectParameter("BultosInv", bultosInv) :
                new ObjectParameter("BultosInv", typeof(double));
    
            var usuarioInventarioParameter = usuarioInventario != null ?
                new ObjectParameter("UsuarioInventario", usuarioInventario) :
                new ObjectParameter("UsuarioInventario", typeof(string));
    
            var hxPInvParameter = hxPInv.HasValue ?
                new ObjectParameter("HxPInv", hxPInv) :
                new ObjectParameter("HxPInv", typeof(int));
    
            var cajasSueltasInvParameter = cajasSueltasInv.HasValue ?
                new ObjectParameter("CajasSueltasInv", cajasSueltasInv) :
                new ObjectParameter("CajasSueltasInv", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var codigoArticuloParameter = codigoArticulo != null ?
                new ObjectParameter("CodigoArticulo", codigoArticulo) :
                new ObjectParameter("CodigoArticulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("INV_dPosiciones_Update", idParameter, usuarioParameter, digitoParameter, bultosInvParameter, usuarioInventarioParameter, hxPInvParameter, cajasSueltasInvParameter, observacionesParameter, codigoArticuloParameter);
        }
    }
}
