export class Posicion {
  constructor(
    public id: number,
    public documento: string,
        public sector: string,
        public pasillo: string,
        public columna: string,
        public nivel: string,
        public compart: string,
        public etiqueta: string,
        public dun14: string,
        public descripcion: string,
        public proveedor: string,
        public id_orden_compra: string,
        public fecha_hora_recepcion: string,
        public vencimiento: string,
        public vidautil: string,
        public diasvencer: string,
        public cxh: string,
        public hxp: string,
        public uxb: string,
        public uxpack: string,
        public bultos: string,
        public packs: string,
        public unidades: string,
        public recepcionista: string,
        public almacenador: string,
        public estadocalidad: string,
        public cara: string,
        public metodo: string,


        public usuario: string,
        public digito: string,
        public bultosinv: number,
        public ts: Date,
        public fechaact: Date,
        public usuarioinventario: string,
        public tipoinventario: string,
        public hxpinv: number,
        public cajassueltasinv: number,
        public estado: string,
        public observaciones: string,

        public ean13: string,
        public codigoarticulo: string,
        public tipolectura: string,
        public documentoasociado: string)
    { }
}
